### ISSUE TITLE
dev packages aren't installed from sub-projects

### ISSUE THREAD

**Issue by gemmell** [TechnologyBrewery/poetry-monorepo-dependency-plugin#20]
Firstly, thank you for finally putting in a good solution to managing monorepos. It seems very useful thus far.

The only problem I've hit is that if I have dev dependencies in my nested packages, installing a top level package that includes that doesn't include that group. 

```toml
[tool.poetry]
name = "my-package"
version = "0.0.0"
description = "A meta project for my software"
# This is a meta project, it doesn't have a package associated with it
package-mode = false
authors = ["me"]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
qb-notebook-server = {path = "apps/notebook_server", develop = true}
qb-thing-server = {path = "apps/thing_server", develop = true}

[tool.poetry-monorepo-dependency-plugin]
enable = true

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[build-system]
requires = ["poetry>=1.2.0b1", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

```

Where those sub packages have a pyproject.toml like:
```toml
[tool.poetry]
name = "qb-thing-server"
version = "0.0.0"
description = "A RESTful server that provides ..."
authors = ["Me"]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
fastapi = "^0.109.0"
uvicorn = {extras = ["standard"], version = "^0.18.2"}
websockets = "^12.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-xdist = "^3.5.0"
pytest-asyncio = "^0.20.3"
asgi-lifespan = ">=2.1.0"
pytest_async = "^0.1.1"
requests = "^2.31.0"
httpx = "^0.23.0"
pydantic = "^2.5.3"
anyio = "<4"

[tool.poetry-monorepo-dependency-plugin]
enable = true

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[build-system]
requires = ["poetry>=1.2.0b1", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
```

The problem is that the dev dependencies of the nested group don't get installed. What I would like is for this plugin to be smart enough to pass down the groups to sub-packages?

For now I've worked around it by moving the dev packages to the top level pyproject.toml.
