### ISSUE TITLE
Update build and release to use actions/setup-python rather than gabrielfalcao/pyenv-action for faster builds

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/poetry-monorepo-dependency-plugin#27]
The following code snippets seem more appropriate for GitHub Actions and result in 2-4 minute faster builds than using pyenv (which is still preferable locally or in long-running environments).
```
      - name: Install Python # use direct install rather than pyenv for CI for large speed improvement
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'
```
and
```
 -Dhabushu.usePyenv=false
```

## Results
Build improved from about ~2m 30s on average to ~50s on average
