### ISSUE TITLE
sdist functionality

### ISSUE THREAD

**Issue by keriksson-rosenqvist-oqc** [TechnologyBrewery/poetry-monorepo-dependency-plugin#9]
Based on the package name I was hoping that this package would replace path dependencies for both wheel and sdist builds but from quick testing it seems only wheel builds are updated. Is there intent to have sdist builds functionality as well?

**Comment by d-ryan-ashcraft** [comment]
Pulled the [`habushu-mixology-comsumer` artifacts](https://github.com/TechnologyBrewery/habushu) from [test.pypi.org](https://test.pypi.org/project/habushu_mixology_consumer) to see what is going on:
* `wheel` files are making the substitution, as expected.  For instance, from the contents of `METADATA`:
```
Metadata-Version: 2.1
Name: habushu_mixology_consumer
Version: 2.14.0.dev1715088202
...
Requires-Dist: habushu_mixology (==2.14.0.*)
```
* Similarly, we see the same in the `sdist`.  For instance, from the contents of `PKG-INFO`:
```
Metadata-Version: 2.1
Name: habushu_mixology_consumer
Version: 2.14.0.dev1715088202
...
Requires-Dist: habushu_mixology (==2.14.0.*)
```
* **However**, the `sdist` also has a `pyproject.toml` that is **NOT** getting the mono-repo dependency substituted, but **IS getting the version of the module itself substituted:**
```toml
[tool.poetry]
name = "habushu_mixology_consumer"
version = "2.14.0.dev1715088202"
...
[tool.poetry.dependencies]
habushu-mixology = {path = "../habushu-mixology", develop = true}
```
